### ISSUE TITLE
Spacing in corporate block footer is not aligend

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_whitelabel#285]
In the corporate block, the top spacing for the sections in the footer is not aligned with the spacing for site name.
This is due to the fact that we have `mt-3` applied on the title of the sections: See https://github.com/openeuropa/oe_whitelabel/blob/1.x/templates/overrides/navigation/oe-corporate-blocks-neutral-footer.html.twig

![image](https://github.com/openeuropa/oe_whitelabel/assets/15343499/6bb97b0f-ee8b-4a3b-b068-90c3253b1442)

**Comment by brummbar** [comment]
Is this fixed by #289  ?

**Comment by msnassar** [comment]
> Is this fixed by #289 ?

The issue has been fixed. Thanks :)

**Comment by msnassar** [comment]
Sorry, I just noticed https://github.com/openeuropa/oe_whitelabel/issues/289 doesn't fix this issue... I thought it is, but it seems we have a local patch fixing it :)
The PR for https://github.com/openeuropa/oe_whitelabel/issues/289 is fixing the spacing for legal and institution links title. 
This issue is about the title of the top footer sections...
https://github.com/openeuropa/oe_whitelabel/blob/1.x/templates/overrides/navigation/oe-corporate-blocks-neutral-footer.html.twig#L20
https://github.com/openeuropa/oe_whitelabel/blob/1.x/templates/overrides/navigation/oe-corporate-blocks-neutral-footer.html.twig#L31
